//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmailService.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Your Request For Leave Is Approved&lt;/title&gt;
        ///  &lt;style&gt;
        ///table {
        ///  font-family: arial, sans-serif;
        ///  border-collapse: collapse;
        ///  width: 100%;
        ///}
        ///
        ///td, th {
        ///  border: 1px solid #dddddd;
        ///  text-align: left;
        ///  padding: 8px;
        ///}
        ///
        ///tr:nth-child(even) {
        ///  background-color: #dddddd;
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;p style=&quot;color:grey;&quot;&gt;&lt;u&gt;YOUR REQUEST FOR LEAVE IS APPROVED.&lt;/u&gt;&lt;/p&gt;
        ///    &lt;p&gt;Hello, Employee Name&lt;/p&gt;
        ///
        ///    &lt;p&gt;Your Leave Request has been approved.
        ///        &lt;br&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LeaveApprovedTemplate {
            get {
                return ResourceManager.GetString("LeaveApprovedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Your Request For Leave Is Approved&lt;/title&gt;
        ///  &lt;style&gt;
        ///table {
        ///  font-family: arial, sans-serif;
        ///  border-collapse: collapse;
        ///  width: 100%;
        ///}
        ///
        ///td, th {
        ///  border: 1px solid #dddddd;
        ///  text-align: left;
        ///  padding: 8px;
        ///}
        ///
        ///tr:nth-child(even) {
        ///  background-color: #dddddd;
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;p style=&quot;color:grey;&quot;&gt;&lt;u&gt;YOUR REQUEST FOR LEAVE IS REJECTED.&lt;/u&gt;&lt;/p&gt;
        ///    &lt;p&gt;Hello, Employee Name&lt;/p&gt;
        ///
        ///    &lt;p&gt;Your Leave Request has been rejected.
        ///        &lt;br&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LeaveRejectedTemplate {
            get {
                return ResourceManager.GetString("LeaveRejectedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;New Leave Request&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///    &lt;p&gt;Hi {1},&lt;/p&gt;
        ///
        ///    &lt;p&gt;{0}&apos;s Leave Request is waiting for your approval.
        ///        &lt;br&gt;&lt;br&gt;
        ///        Start Date: {2}
        ///        &lt;br&gt;
        ///        End Date: {3}
        ///        &lt;br&gt;
        ///        Total Days: {4}
        ///        &lt;br&gt;
        ///        Reason for Leave : {5}
        ///    &lt;/p&gt;
        ///    &lt;p&gt; Please Click &lt;a href=&quot;https://employeeleavestracking.azurewebsites.net/&quot;&gt;Here&lt;/a&gt; to Approve/Reject.&lt;/p&gt;
        ///
        ///    &lt;p&gt; Thankyou
        ///        &lt;br&gt; ------------
        ///        &lt;br&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LeaveRequestTemplate {
            get {
                return ResourceManager.GetString("LeaveRequestTemplate", resourceCulture);
            }
        }
    }
}
